DROP TABLE DEPT_TEMP;
-- 10-1) DEPT 테이블을 복사해서 DEPT_TEMP 테이블 만들기
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;

-- 10-2) DEPT_TEMP 테이블 전체 열 조회하기
SELECT * FROM DEPT_TEMP;

-- 10-3) DEPT_TEMP 테이블에 데이터 추가하기
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_TEMP;

-- 10-4) INSERT문에 열 지정 없이 데이터 추가하기
INSERT INTO DEPT_TEMP VALUES(60, 'NETWROK', 'BUSAN');
SELECT * FROM DEPT_TEMP;

-- 10-5) NULL을 지정하여 입력하기
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(70, 'WEB', NULL);
SELECT * FROM DEPT_TEMP;

-- 10-6) 빈 공백 문자열로 NULL을 입력하기
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(80, 'MOMILE', '');
SELECT * FROM DEPT_TEMP;

-- 10-7) 열 데이터를 넣지 않는 방식으로 NULL 데이터 입력하기
INSERT INTO DEPT_TEMP(DEPTNO, LOC) VALUES(80, 'INCHEON');
SELECT * FROM DEPT_TEMP;

DROP TABLE EMP_TEMP;

-- 10-8) EMP 테이블을 복사해서 EMP_TEMP 테이블 만들기
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP;

-- 10-9) INSERT문으로 날짜 데이터 입력하기(날짜 사이에 / 입력)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
       VALUES(9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);
SELECT * FROM EMP_TEMP;

-- 10-10) INSERT문으로 날짜 데이터 입력하기(날짜 사이에 - 입력)
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
       VALUES(1111, '성춘향', 'MANAGER', 9999, '2001-01-15', 4000, NULL, 20);
SELECT * FROM EMP_TEMP;

-- 10-11) 날짜 데이터 형식을 반대로 했을 때
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
       VALUES(2111, '이순신', 'MANAGER', 9999, '07/01/2001', 4000, NULL, 20);

-- 10-12) 날짜 데이터 형식을 반대로 했을 때
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
       VALUES(2111, '이순신', 'MANAGER', 9999, TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);
SELECT * FROM EMP_TEMP;

-- 10-13) SYSDATE를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
       VALUES(3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);
SELECT * FROM EMP_TEMP;

-- 10-14) 서브쿼리로 여러 데이터 추가하기
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
       SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAl, E.COMM, E.DEPTNO
       FROM EMP E, SALGRADE S
       WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
       AND S.GRADE = 1;
SELECT * FROM EMP_TEMP;

DROP TABLE DEPT_TEMP2;

-- 10-15) DEPT 테이블을 복사해서 DEPT_TEMP2 테이블 만들기
CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP2;

-- 10-16) DEPT_TEMP2 테이블 업데이트하기
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL';
SELECT * FROM DEPT_TEMP2;

-- 10-17) ROLLBACK으로 테이블 내용을 이전 상태로 되돌리기
ROLLBACK;
SELECT * FROM DEPT_TEMP2;

-- 10-18) 테이블 데이터 중 일부분만 수정하기 
UPDATE DEPT_TEMP2 SET DNAME = 'DATABASE', LOC = 'SEOUL' WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

-- 10-19) 서브쿼리로 데이터 일부분 수정하기
UPDATE DEPT_TEMP2 SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40) WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

-- 10-20) 서브쿼리로 데이터 일부분 수정하기
UPDATE DEPT_TEMP2 SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
                     LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

-- 10-21) UPDATE문의 WHERE 절에 서브쿼리 사용하기
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL' WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME = 'OPERATIONS');
SELECT * FROM DEPT_TEMP2;

DROP TABLE EMP_TEMP2;

-- 10-22) EMP테이블을 복사해서 EMP_TMEP2 테이블 만들기
CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP2;

-- 10-23 WHERE 절을 사용하여 데이터 일부분만 삭제하기
DELETE FROM EMP_TEMP2 WHERE JOB = 'MANAGER';
SELECT * FROM EMP_TEMP2;

-- 10-24) WHERE절에 서브쿼리를 사용하여 데이터 일부만 삭제하기
DELETE FROM EMP_TEMP2 WHERE EMPNO IN (SELECT E.EMPNO FROM EMP_TEMP2 E, SALGRADE S
                                      WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                                      AND S.GRADE = 3 AND DEPTNO =30);
SELECT * FROM EMP_TEMP2;

-- 10-25) 테이블에 있는 전체 데이터 삭제하기
DELETE FROM EMP_TEMP2;
SELECT * FROM EMP_TEMP2;

DROP TABLE DEPT_TCL;

-- 11-1) DEPT 테이블을 복사해서 DEPT_TCL 테이블 만들기
CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TCL;

-- 11-2) DEPT_TCL 테이블에 데이터를 입력, 수정 삭제하기
INSERT INTO DEPT_TCL VALUES(50, 'DATSABASE', 'SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';
SELECT * FROM DEPT_TCL;

-- 11-3) ROLLBACK으로 명령어 실행 취소하기
ROLLBACK;
SELECT * FROM DEPT_TCL;

-- 11-4) DEPT_TCL 테이블에 데이터를 입력 수정하기
INSERT INTO DEPT_TCL VALUES(50, 'NETWORK', 'SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;
DELETE FROM DEPT_TCL WHERE DEPTNO = 40;
SELECT * FROM DEPT_TCL;

-- 11-5) COMMIT으로 명령어 반영하기
COMMIT;

-- 11-6) 토드와 SQL*PLUS로 세션 알아보기
SELECT * FROM DEPT_TCL;

-- 11-7) 토드와 SLQ*PLUS로 세션 알아보기
DELETE FROM DEPT_TCL WHERE DEPTNO = 50;
SELECT * FROM DEPT_TCL;

-- 11-8) 토드와 SQL*PLUS로 세션 알아보기 
COMMIT;
SELECT * FROM DEPT_TCL;

-- 11-9) 토드와 SQL*PLUS로 LOCK 알아보기
SELECT * FROM DEPT_TCL;

-- 11-10) 토드와 SQL*PLUS로 LOCK 알아보기
UPDATE DEPT_TCL SET LOC = 'SEOUL' WHERE DEPTNO = 30;
SELECT * FROM DEPT_TCL;

-- 11-11) 토드와 SQL*PLUS로 LOCK 알아보기
-- 토드에서는 아무 작업 안 함

-- 11-12) 토드와 SQL*PLUS로 LOCK 알아보기
COMMIT;

-- 11-13) 토드와 SQL*PLUS로 LOCK 알아보기 
SELECT * FROM DEPT_TCL;

-- 11-14) 토드와 SQL*PLUS로 LOCK 알아보기 - 세션 B(SQL*PLUS)

-- 11-15) 토드와 SQL*PLUS로 LOCK 알아보기 - 세션 A(토드)
SELECT * FROM DEPT_TCL;

-- 12-1) 모든 열의 각 자료형을 정의해서 테이블 생성하기
CREATE TABLE EMP_DDL(
    EMPNO       NUMBER(4),
    ENNAME      VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
);
DESC EMP_DDL;

-- 12-2) 다른 테이블을 복사하여 테이블 생성하기
CREATE TABLE DEPT_DDL AS SELECT * FROM DEPT;
DESC DEPT_DDL;

-- 12-3) DEPT_DDL 테이블 전체 조회하기
SELECT * FROM DEPT_DDL;

-- 12-4) 다른 테이블의 일부를 복사하여 테이블 생성하기
CREATE TABLE EMP_DDL_30 AS SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP_DDL_30;

-- 12-5) 다른 테이블을 복사하여 테이블 생성하기(열 구조만 복사하기)
CREATE TABLE EMPDEPT_DDL
    AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE 1 <> 1;
SELECT * FROM EMPDEPT_DDL;

-- 12-6) EMP 테이블을 복사하여 EMP_ALTER 테이블 생성하기
CREATE TABLE EMP_ALTER AS SELECT * FROM EMP;
SELECT * FROM EMP_ALTER;

-- 12-7) ALTER 명령어로 HP 열 추가하기
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20);
SELECT * FROM EMP_ALTER;

-- 12-8) ALTER 명령어로 HP 열 이름을 TEL로 변경하기
ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;
SELECT * FROM EMP_ALTER;

-- 12-9) ALTER 명령어로 EMPNO 열 길이 변경하기
ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;

-- 12-10) ALTER 명령어로 TEL 열 삭제하기
ALTER TABLE EMP_ALTER DROP COLUMN TEL;
SELECT * FROM EMP_ALTER;

-- 12-11) 테이블 이름 변경하기
RENAME EMP_ALTER TO EMP_RENAME;

-- 12-12) 바꾸기 전 이름을 테이블 구성 살펴보기
DESC EMP_ALTER;

-- 12-13) 변경된 테이블이름(EMP_RENAME)으로 조회
SELECT * FROM EMP_RENAME;

-- 12-14) EMP_RENAME 테이블의 전체 데이터 삭제하기
TRUNCATE TABLE EMP_RENAME;
SELECT * FROM EMP_RENAME;

-- 12-15) EMP_RENAME 테이블 삭제하기
DROP TABLE EMP_RENAME;

-- 12-16) EMP_RENAME 테이블 구성 살펴보기
DESC EMP_RENAME;

